# Minimal type stubs for SPIKE Prime runtime to satisfy editors (pylance/pyright)
from typing import Any

class PrimeHub:
    def __init__(self) -> None: ...

class Motor:
    def __init__(self, port: str) -> None: ...
    def run_for_rotations(self, rotations: float, speed: int, *args: Any, **kwargs: Any) -> None: ...
    def run_for_degrees(self, degrees: int, speed: int, *args: Any, **kwargs: Any) -> None: ...
    def start(self, speed: int) -> None: ...
    def stop(self) -> None: ...

class MotorPair:
    PAIR_1: int
    def __init__(self, a: str, b: str) -> None: ...
    def move_tank(self, amount: int, unit: str, left: int, right: int) -> None: ...
    def start_tank(self, left: int, right: int) -> None: ...
    def move(self, pair_id: int, angle: int, velocity: int = ...) -> None: ...
    def stop(self) -> None: ...
